name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Decode kubeconfig and save to file
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBE_CONFIG_BASE64 }}" | base64 -d > ~/.kube/config

    - name: Apply Kubernetes Deployment
      run: kubectl apply -f playwright-deployment.yaml
