name: Docker Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t playwright-tests .

    - name: Run a specific Playwright test inside container
      run: docker run --rm playwright-tests npx playwright test tests/Google.spec.js