name: Playwright Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Fix Playwright permission (optional safety step)
        run: chmod +x ./node_modules/.bin/playwright

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run only login test
        run: npx playwright test tests/Google.spec.js

      - name: Upload HTML Report
        if: always()  # Always upload report even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report
          path: playwright-report/
